# Generated by Django 6.0.6 on 2026-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumematchresultmodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
