# Generated by Django 6.0.6 on 2026-07-13 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_alter_resumematchresultmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumematchresultmodel',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 7, 13, 22, 16, 29, 502959)),
        ),
    ]
