# Generated by Django 6.0.6 on 2026-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_alter_resumematchresultmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumematchresultmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
