# Generated by Django 6.0.6 on 2026-09-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_resumebuildtemplate_updated_at_userresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumebuildtemplate',
            name='preview_image',
        ),
    ]
