import '../assets/style/about.css'
import { useEffect, useRef, useState } from 'react'

function useInView(threshold = 0.15) {

    const ref = useRef(null)
    const [inView, setInView] = useState(false)

    useEffect(() => {
        const node = ref.current
        if (!node) return
        const observer = new IntersectionObserver(
            ([entry]) => {
                if (entry.isIntersecting) {
                    setInView(true)
                    observer.unobserve(node)
                }
            },
            { threshold }
        )
        observer.observe(node)
        return () => observer.disconnect()
    }, [threshold])

    return [ref, inView]
}

const LockShieldIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 5 6v6c0 4.2 3 7.8 7 9 4-1.2 7-4.8 7-9V6l-7-3Z" /><rect x="9.2" y="11" width="5.6" height="4.4" rx="1" /><path d="M10.3 11V9.6a1.7 1.7 0 0 1 3.4 0V11" /></svg>
)
const NoStoreIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="7" ry="2.5" /><path d="M5 6v5c0 1.4 3.1 2.5 7 2.5M19 9.5V6" /><path d="M5 11v5c0 1.4 3.1 2.5 7 2.5.9 0 1.8-.08 2.6-.24" /><path d="m4 4 16 16" /></svg>
)
const TextOnlyIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 3h7l5 5v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z" /><path d="M14 3v5h5" /><path d="M9 13h6M9 16.5h6M9 9.5h2" /></svg>
)
const InfoIcon = () => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9" /><path d="M12 11v5.5M12 8v.01" /></svg>
)

const STEPS = [
    {
        title: "Create Your Account",
        text: "Register with your email to unlock the dashboard, saved history and the resume builder.",
    },
    {
        title: "Log In",
        text: "Sign back in any time — your dashboard, uploads and saved resumes stay private to your account.",
    },
    {
        title: "Open Your Dashboard",
        text: "See your past analyses, saved resumes and quick shortcuts to every tool in one place.",
    },
    {
        title: "Upload Your Resume",
        text: "Drop in a PDF, DOCX or TXT file. The text is extracted automatically — the file itself is never stored.",
    },
    {
        title: "Add a Job Description",
        text: "Paste the JD text or upload a file. Personal details are stripped before anything is analyzed.",
    },
    {
        title: "Get Your Results",
        text: "View your match percentage, missing skills, ATS score and improvement suggestions within seconds.",
    },
    {
        title: "Build a New Resume",
        text: "Choose a template, fill in each section — contact, summary, experience, education, skills, projects — preview it live, and download it as a polished PDF.",
    },
]

const TERMS = [
    {
        title: "Acceptable Use",
        text: "Use ResumeIQ only for genuine job-search purposes. Don't upload documents you don't have the right to share, or try to use the AI analysis tools for anything unrelated to resumes and job matching.",
    },
    {
        title: "Your Account",
        text: "You're responsible for keeping your login credentials secure and for any activity that happens under your account.",
    },
    {
        title: "AI & Third-Party Processing",
        text: "Resume and job-description text — with personal details removed — is sent to Google's Gemini API for analysis. Uploaded files are never stored; only the extracted, anonymized text is processed, and only for the length of your request.",
    },
    {
        title: "Your Content",
        text: "You keep ownership of any resume or document you upload or create here. It's used only to generate your analysis or resume, never for any other purpose.",
    },
    {
        title: "No Warranty",
        text: "Match scores and suggestions are generated by an AI model and are meant as guidance only. They don't guarantee an interview or job outcome.",
    },
    {
        title: "Changes to These Terms",
        text: "ResumeIQ is a student project under active development, so these terms and the platform's features may evolve over time.",
    },
]

function About() {
    const [heroRef, heroIn] = useInView(0.1)
    const [flowHeadRef, flowHeadIn] = useInView(0.15)
    const [privacyHeadRef, privacyHeadIn] = useInView(0.15)
    const [atsRef, atsIn] = useInView(0.15)
    const [termsHeadRef, termsHeadIn] = useInView(0.15)

    return (
        <main>


            <div ref={heroRef} className={`about-hero reveal ${heroIn ? "in-view" : ""}`}>
                <span className="section-eyebrow">About ResumeIQ</span>
                <h1>About <span className="gradient-text">ResumeIQ</span></h1>
                <p className="about-lead">
                    ResumeIQ helps you build a professional resume and instantly see how well it matches
                    any job description. Upload your resume, add a job description, and get a detailed
                    breakdown — match score, missing skills, ATS section coverage and clear suggestions
                    to improve it.
                </p>
                <p className="about-lead">
                    Text is extracted from your documents and analyzed with Google's Gemini AI, with your
                    personal details removed first and your original files never kept on our servers.
                </p>
            </div>

            <section className="about-section">
                <div ref={flowHeadRef} className={`section-head reveal ${flowHeadIn ? "in-view" : ""}`}>
                    <span className="section-eyebrow">Getting Started</span>
                    <h2>How This Website Works</h2>
                    <p>From creating an account to downloading a polished resume — here's the full journey, step by step.</p>
                </div>

                <div className="flow-timeline">
                    {STEPS.map((step, i) => {
                        const [ref, inView] = useInView(0.2)
                        return (
                            <div
                                key={step.title}
                                ref={ref}
                                className={`flow-step reveal ${inView ? "in-view" : ""}`}
                                style={{ transitionDelay: inView ? `${i * 70}ms` : "0ms" }}
                            >
                                <div className="flow-num">{i + 1}</div>
                                <div className="flow-content">
                                    <h4>{step.title}</h4>
                                    <p>{step.text}</p>
                                </div>
                            </div>
                        )
                    })}
                </div>
            </section>

            <section className="about-section">
                <div ref={privacyHeadRef} className={`section-head reveal ${privacyHeadIn ? "in-view" : ""}`}>
                    <span className="section-eyebrow">Your Privacy</span>
                    <h2>Your Data, Handled Carefully</h2>
                    <p>A few rules we follow on every upload and every analysis, without exception.</p>
                </div>

                <div className="privacy-grid">
                    <div className="privacy-card">
                        <div className="privacy-icon pi-1"><LockShieldIcon /></div>
                        <h4>No Personal Data to the AI</h4>
                        <p>Before any text reaches the AI model, we automatically remove personally identifiable
                            details like your name, phone number, email and address.</p>
                    </div>
                    <div className="privacy-card">
                        <div className="privacy-icon pi-2"><NoStoreIcon /></div>
                        <h4>Your File Is Never Saved</h4>
                        <p>We only read the text inside your resume. Uploaded files exist for the length of the
                            request and are discarded immediately after processing.</p>
                    </div>
                    <div className="privacy-card">
                        <div className="privacy-icon pi-3"><TextOnlyIcon /></div>
                        <h4>Text-Only Processing</h4>
                        <p>Only the extracted, anonymized text is sent for analysis — never the original document,
                            images or file metadata.</p>
                    </div>
                </div>

                <div className="privacy-note">
                    <InfoIcon />
                    <span>In short: we work with the words on your resume, not the file itself — and never with your personal identifying details.</span>
                </div>
            </section>

            <section id="terms" className="about-section terms-section">
                <div ref={termsHeadRef} className={`section-head reveal ${termsHeadIn ? "in-view" : ""}`}>
                    <span className="section-eyebrow">Legal</span>
                    <h2>Terms of Service</h2>
                    <p>The short version of what you're agreeing to by using ResumeIQ.</p>
                </div>

                <div className="terms-block">
                    {TERMS.map((term, i) => (
                        <div key={term.title} className="terms-item">
                            <h4><span className="tnum">{String(i + 1).padStart(2, "0")}</span> {term.title}</h4>
                            <p>{term.text}</p>
                        </div>
                    ))}
                </div>
            </section>

            <div className="about-footnote">
                By using ResumeIQ, you agree to our{" "}
                <a href="/about#terms">Terms of Service</a>.
            </div>

        </main>
    )
}

export default About